### ISSUE TITLE
DRY: isNumeric() function 

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#10]
Do not Repeat Youself

you define isNumeric again and again:
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/5e7df2e37a5162add480901d682a01cecda6665f/commands/Admin/_edit-bonus.js#L17

`function isNumeric(n) {
  return !isNaN(parseFloat(n)) && isFinite(n)
}`

Please move it to before all command

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/f837f3bcceab602a22e2f68f2e103a227599d2b6
