### ISSUE TITLE
Still bad naming

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#12]
then you have
if (user.telegramid == admin) {

so it is NOT admin_chat!

it is adminTgId !

_Originally posted by @bots-business in https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/issues/9#issuecomment-945059472_

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/c1a4cb0c170503de326b0e94263fa1dd96c47d63
