### ISSUE TITLE
Use folder in BJS: we can check admin more effective now

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#13]
Please see - https://t.me/botsbus/1215

It is possible to check admin in before all command now!

**Comment by Untoldhacker-Dev** [comment]
**https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/6ec2c2cd1368b60e3d58f0adf47e32dc4fc9e326**
