### ISSUE TITLE
Still bad names for variables

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#14]
You still have bad names! 

```
 var admin_chat = Bot.getProperty("admin_chat")
  if ( command.folder == "Admin" && admin_chat == user.telegramid )
```

**What it is?**
admin_chat == user.telegramid

chat it is not telegramid! 
Use adminTgID here

Really "admin_chat" name is worst.
It can be:
- chat with admin - String, Integer
- chat for admins - String, Integer
- other things

Do not use such bad names. 
It is magic!

Please check all codes for this and fix.

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/768850869754fa06012646931855cd152bc3e5a3
