### ISSUE TITLE
Still Bad folders naming

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#15]
![image](https://user-images.githubusercontent.com/38240269/137825061-f1380bcc-cdf8-464a-a288-f728d8e24434.png)

and in Main Menu Options we have:
![image](https://user-images.githubusercontent.com/38240269/137825127-142e0f71-bdfc-4fd5-a6a2-1a489981c288.png)

What about another folder like Wallet, Referral or/and etc? 

Main Menu Options it is bad name I think.
Because we have only 1 command in Main Menu. And it is /start!

**Comment by Untoldhacker-Dev** [comment]
Other folders like: Referal etc will also have only one commands.....

**Comment by bots-business** [comment]
> Other folders like: Referal etc will also have only one commands.....

But we can add new commands in future.

**Comment by Untoldhacker-Dev** [comment]
Now, PR - https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/24 Fixed.

**Comment by Untoldhacker-Dev** [comment]
Now, PR - https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/24 Fixed.
