### ISSUE TITLE
Make common variable.

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#16]
You have this code:

```
var currency = Bot.getProperty("cur")
let balance = Libs.ResourcesLib.userRes("balance")
var wallet = User.getProperty("wallet")
```

in several files. Like /withdraw, /bonus

### Possible fix.

Move this to @ command:

```
user.balance = Libs.ResourcesLib.userRes("balance");
user.wallet = User.getProperty("wallet");
```

then you can use `user.balance` and `user.wallet` in any command 

### Cur fix

What it is cur? It is bad name!
I think it is currency name. True?

```
then in @ command:
bot.currencyName = Bot.getProperty("currencyName")
```

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/7c745c07283899960e8f33c9f65a1530033b4c10
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/8e59a699bd0cb439e5a68744997455d3812355e1
