### ISSUE TITLE
Use BB Admin Panel for all Bot's options

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#17]
You have min and cur in bot now. 
And others?

You can use admin panel for this option:
https://help.bots.business/bjs/admin-panel

Also please note!
**min and cur - it is bad names!**

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/768850869754fa06012646931855cd152bc3e5a3
