### ISSUE TITLE
Use time resource

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#18]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/00192caac633d05ea73091d2099cd624dbbaec8c/commands/Main%20Menu%20Options/_bonus.js#L14

```
  var last_run_at = User.getProperty("last_run_atr")
  if (!last_run_at) {
    return true
  }

  var minutes = (Date.now() - last_run_at) / 1000 / 60

  var minutes_in_day = 24 * 60
  var next = minutes_in_day - minutes
  var wait_hours = Math.floor(next / 60)
  next -= wait_hours * 60
  var wait_minutes = Math.floor(next)
  var seconds = Math.floor((next - wait_minutes) * 60)
```

It is very difficult code. 
It can be more easy with Resource: https://help.bots.business/libs/resourceslib#growth-for-resource.

**Comment by Untoldhacker-Dev** [comment]
Oh, ya, nice idea, updating code...

**Comment by Untoldhacker-Dev** [comment]
But bonus should be manually claimable so that users can **miss** it too if they are inactive, this code is common one: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/00192caac633d05ea73091d2099cd624dbbaec8c/commands/Main%20Menu%20Options/_bonus.js#L14

And also with [that code](https://help.bots.business/libs/resourceslib#growth-for-resource), when user clicks on Bonus command, then he will recieve it in the next 24 hours.....??

**Comment by bots-business** [comment]
Set Res with 24*60*60 value

Then add to this Res negative growth -1 every second. With min value = 0

if user click on bonus:
- Res value > 0 - no bonus
- Res value = 0 - bonus! 

On bonus:
- add bonus to user
- Set Res with 24*60*60 value again!

So negative growth will be works again and again!

**Comment by Untoldhacker-Dev** [comment]
🤔 ok, I'll make like this-
Bonus - 
Answer:- your bonus adding has been started, Your balance will be automatically updated every 24 hours
Bjs - As described

But then, it won't be daily bonus, infact, it should not be automatic, else if user be inactive on bot then also he can get the money

**Comment by Rohan487** [comment]
Solution is using Epoch Milliseconds

The Unix epoch milliseconds is the number of milliseconds that have elapsed since January 1, 1970

So Epoch will be always increasing It will reduce the work to find how much seconds left for 24hour.

Epoch in BB -> `var epochmilliseconds = Date.now();`

Date.now() returns current time in milliseconds example - 1634749091760 

Epoch is a unique value that will never repeat itself so it is unique.

Save the Epoch while giving the user bonus.
```
var claimed_time = Date.now();
User.setProperty('last_run_at',claimed_time,'int');

```

Now for checking the next bonus.
To add a verification that 24 hour passed or not just use it like below;

```
var last_run_at = User.getProperty('lastrunat');
var current_time = Date.now();
var difference = current_time - last_run_at;

If(difference < 86400000){
//Send error msg;
return;
}

//proceed Give bonus 
```

In the above code 86400000 is Milliseconds in one day 

Hope you All understand this easy process 

Bonus Tip:

You can convert any epoch milliseconds to Local Date using below BB code 
```
var last_run_at = User.getProperty('last_run_at');
var last_bonus_claimed_date = new Date(last_run_at).toLocalDateString();

```
//Display Decorated message with the date when user claimed last bonus or do whatever you want

**Comment by bots-business** [comment]
> Solution is using Epoch Milliseconds
> 
> The Unix epoch milliseconds is the number of milliseconds that have elapsed since January 1, 1970
> 
> So Epoch will be always increasing It will reduce the work to find how much seconds left for 24hour.
> 
> Epoch in BB -> `var epochmilliseconds = Date.now();`
> 
> Date.now() returns current time in milliseconds example - 1634749091760
> 
> Epoch is a unique value that will never repeat itself so it is unique.
> 
> Save the Epoch while giving the user bonus.
> 
> ```
> var claimed_time = Date.now();
> User.setProperty('last_run_at',claimed_time,'int');
> ```
> 
> Now for checking the next bonus. To add a verification that 24 hour passed or not just use it like below;
> 
> ```
> var last_run_at = User.getProperty('lastrunat');
> var current_time = Date.now();
> var difference = current_time - last_run_at;
> 
> If(difference < 86400000){
> //Send error msg;
> return;
> }
> 
> //proceed Give bonus 
> ```
> 
> In the above code 86400000 is Milliseconds in one day
> 
> Hope you All understand this easy process
> 
> Bonus Tip:
> 
> You can convert any epoch milliseconds to Local Date using below BB code
> 
> ```
> var last_run_at = User.getProperty('last_run_at');
> var last_bonus_claimed_date = new Date(last_run_at).toLocalDateString();
> ```
> 
> //Display Decorated message with the date when user claimed last bonus or do whatever you want

I am still think that ResLib with growth is more effective and easy

**Comment by Rohan487** [comment]
@bots-business 

ResLib is depends on The BB server if server will down for some reason then it can affect the Growth process.

May be Growth will stop if server will be down for some reason.

I think using `date.now()` is effective way to avoid server outage cause Time will be always increasing it doesn't matter if server down or not.

**Comment by bots-business** [comment]
Set Res with 246060 value

Then add to this Res negative growth -1 every second. With min value = 0

if user click on bonus:

Res value > 0 - no bonus
Res value = 0 - bonus!
On bonus:

add bonus to user
Set Res with 246060 value again!

**Comment by bots-business** [comment]
Please see - Q: How to make time limit bonus?
https://help.bots.business/libs/resourceslib#q-how-to-make-time-limit-bonus

**Comment by Untoldhacker-Dev** [comment]
Fixing.

Also: Adding Changing Bonus Time from INApp admin panel.
Update within 2-3 hrs.

Src: [BB Help Docs](https://help.bots.business/libs/resourceslib#q-how-to-make-time-limit-bonus)
```
let bonusCooldown = Libs.ResourcesLib.userRes("bonusCooldown");

// cooldown in seconds
let totalCooldown = 60*60*5; // 60*60*5 seconds = 5 hours

function resetCooldown(){
   bonusCooldown.set(totalCooldown); 
}

function setupCooldown(){
  if(bonusCooldown.growth.isEnabled()){
     // already setupped
     return
  }
  
  bonusCooldown.growth.add({
    value: -1,  // just add negative value
    interval: 1, // -1 once at 1 sec
    min: 0
  });
}

setupCooldown();

if(bonusCooldown.value() > 0){
   Bot.sendMessage("Please wait: " + bonusCooldown.value() + " secs" );
   return
}
 
// can give bonus now
resetCooldown(); // need to reset cooldown

Bot.sendMessage("You have bonus now");
// your other code here
//..
```

**Comment by Untoldhacker-Dev** [comment]
### Updated.
@ PR: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/25
