### ISSUE TITLE
Remove if(!isAdmin()){return} in admin's folder

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#19]
You do not need in Admin's folder now:

`if(!isAdmin()){return}
`

because you have https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/issues/13

need to remove this lines in all files on Admin directory

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/148952e248891886ce8e8e654fd96264241bb8af

**Comment by Untoldhacker-Dev** [comment]
Now `if(!isAdmin()){return}` is removed from admin commands.

**Comment by bots-business** [comment]
I do not see any remov in thus comment: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/148952e248891886ce8e8e654fd96264241bb8af
