### ISSUE TITLE
Need folders for commands

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#2]
Folders it is pretty for organization

**Comment by Untoldhacker-Dev** [comment]
Created: [command-functions](https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/tree/BB_Export_1634291956/command-functions)

**Issue closed.**

**Comment by Untoldhacker-Dev** [comment]
Created: [command-functions](https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/tree/BB_Export_1634291956/command-functions)

**Issue closed.**
