### ISSUE TITLE
User can have blank first_name

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#20]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/00192caac633d05ea73091d2099cd624dbbaec8c/commands/Main%20Menu%20Options/_balance.js#L17

User can have blank first_name. Also he can have any "_", "*" in first name. So murkup will be broken.

I think you need to use method getLinkFor in Commonl lib here: 
https://github.com/bots-business/store-libs/blob/master/commonLib.js

just install CommonLib and use

**Comment by Untoldhacker-Dev** [comment]
Fixed.
