### ISSUE TITLE
I request on json data use

### ISSUE THREAD

**Issue by Wafiismail27** [Untoldhacker-Dev/friendly-octo-fortnight#21]
Do you know how to change a json data's id

For example : 
I have a data like this :
var data = [
  { name: "Bob", website: "male" },
  { name: "Carol", website: "female" },
  { name: "Ted", website: "male" },
  { name: "Alicw", website: "female" }
]

I want to make it like this : 
var data = [
  { name: "Bob", website: "male" },
  { name: "Ted", website: "male" },
  { name: "Carol", website: "female" },
  { name: "Alicw", website: "female" }
]

I want ted and carol change it's position

Let me know if you can!

**Comment by Untoldhacker-Dev** [comment]
Please look W3Schools related to this.
