### ISSUE TITLE
Use CommonLib

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#26]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/BB_Export_1634291956/commands/Admin/_ban.js

Please use CommonLib for this code:

```
  "Successfully banned: " +
    "[" +
    "User" +
    "]" +
    "(" +
    "tg://user?id=" +
    message +
    ")"
```

**Comment by bots-business** [comment]
+ in file too: 

https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/BB_Export_1634291956/commands/Admin/_unban.js

**Comment by Untoldhacker-Dev** [comment]
@bots-business Ok.

**Comment by Untoldhacker-Dev** [comment]
@bots-business Done

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/c9c6d3a02b15320d95647f86c5c0b8ad8df34de2

https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/c9c6d3a02b15320d95647f86c5c0b8ad8df34de2/commands/Admin/_unban.js#L17

https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/c9c6d3a02b15320d95647f86c5c0b8ad8df34de2/commands/Admin/_ban.js#L17
