### ISSUE TITLE
Global vars from @ for user

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#28]
code from @ now:

```
var user_url = Libs.commonLib.getLinkFor(user)
...
var balance = Libs.ResourcesLib.userRes("balance")
var wallet = User.getProperty("wallet")

```

i think it will be more prettty:

```
function readUserData(){
   if(!user){ return }
   user.link = Libs.commonLib.getLinkFor(user)
   user.balance = Libs.ResourcesLib.userRes("balance")
   user.wallet = User.getProperty("wallet")
}
```

then you can use it in the other commands like:
`Bot.sendMessage(user.balance) `

it is more nice!

**Comment by Untoldhacker-Dev** [comment]
@bots-business Ok. I'll work on this.

**Comment by Untoldhacker-Dev** [comment]
@bots-business Do I need to call the function: readUserData()
In every command for this?

**Comment by bots-business** [comment]
> @bots-business Do I need to call the function: readUserData() In every command for this?

only in @:

```
function readUserData(){
   if(!user){ return }
   user.link = Libs.commonLib.getLinkFor(user)
   user.balance = Libs.ResourcesLib.userRes("balance")
   user.wallet = User.getProperty("wallet")
}

readUserData()
```

I am forget about this

**Comment by bots-business** [comment]
also I think for res you need:
 
 user.balance = Libs.ResourcesLib.userRes("balance").value  ?

**Comment by Untoldhacker-Dev** [comment]
Done: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/42
