### ISSUE TITLE
Undefined user in @

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#29]
in @:

```
// user can be undefined here (sometimes it is possible) - so we can have errors on user.telegramid here
if (command.folder == "Admin" && user.telegramid != Admin) {
  return
}
```

Please see help (updated):
https://app.gitbook.com/s/-LVh0yg9olT-QWqi3AYt/bjs/good-coding-practices#use-folders

**Comment by Untoldhacker-Dev** [comment]
Done: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/42
