### ISSUE TITLE
You do not need to set "id" as UserProp in send-funds-answer.js

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#31]
You have in send-funds-answer.js:
```
var msg = message
var options = {tgid: message}
User.setProperty("id", msg)
Bot.run({command:"onGetIdToSend",options})
```

it can be one line only:
`Bot.run({ command:"onGetIdToSend", { tgid: message } })`

and in command onGetIdToSend:
need to change
`let tgid = User.getProperty("id")`

to
`let tgid = options.tgid`

**Comment by bots-business** [comment]
and why do you need 2 commands here?
why not one command?

**Comment by Untoldhacker-Dev** [comment]
Done: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/42
