### ISSUE TITLE
Unsecure _setup.js 

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#32]
Anybody can run /setup 

I think we need to run setup only one time. 
We can check that panels is not setupped and perform setup

something like this:

```
var isInstalled = AdminPanel.getPanel("Admin Information").fields[0];
if(isInstalled){
   // you need to remove this if you want run setup again
   return
}

old code here
```

**Comment by Untoldhacker-Dev** [comment]
Done: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/ff5f82bc4511e6f54f6a4df3be6b49a3350e47b8
