### ISSUE TITLE
you can pass minimum_withdraw to onVerifiedBalance via options

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#35]
just edit in /withdrow from:

```
var options = {authorised:true} //We need this just to make sure the sequence /withdraw > onVerifiedBalance
Bot.run({command: "onVerifiedBalance",options})
```

to:
`Bot.run({command: "onVerifiedBalance", options: { minimum_withdraw: minimum_withdraw } })`

 {authorised:true}  - is not needed now so we have more pretty code!

it is not neede now:
![image](https://user-images.githubusercontent.com/38240269/140310550-ef7afbb1-ab2e-462d-bd3f-cab7064de198.png)

just use options.minimum_withdraw

and change:
```
if (!options.authorised) {
  return
}
```

to:
if (!options.minimum_withdraw) {
  return
}

**Comment by Untoldhacker-Dev** [comment]
Done: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/42
