### ISSUE TITLE
Not needed /setup run in onVerifiedBalance

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#36]
code:

```
if (!channel || !channel.startsWith("@")) {
  Bot.sendMessage(
    "*Seems You have incorrect Information set In App's Admin panel!*"
  )
  Bot.runCommand("/setup")
  return
}
```

It is bad practice to run /setup on user command

It is possible to verify all admin fields with on_saving command
See: https://help.bots.business/bjs/admin-panel
![image](https://user-images.githubusercontent.com/38240269/140311330-ced409e7-8378-41aa-aae8-437c9f0da228.png)

**Comment by Untoldhacker-Dev** [comment]
Done: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/42
