### ISSUE TITLE
try to use functions in onVerifiedBalance

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#38]
We have not so good bjs now in this command. 
I think it is need to split this code to several functions like:

```
function sendNeedMoreAmount(){
..
}
```

and: 
- sendNeedLessAmount()
- sendSuccessfullyWithdraw()
- sendWithdrawRequest()

**Comment by Untoldhacker-Dev** [comment]
Done: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/42
