### ISSUE TITLE
Emodzi policy

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#4]
Now we have 2 diferent emodzi witing:

👥Main Menu
👥 Main Menu

with and without space. It is not beautiful. 

Need use only writing anywhere.

**Comment by bots-business** [comment]
![image](https://user-images.githubusercontent.com/38240269/137605875-596ecbe4-54ec-4b6e-966c-c9c26d04bf94.png)

and etc

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/aa641628f4cacac3b7ee4732f13c7bf5fa323ce8

Updated BJS in _start.js and renamed ⚙️Set wallet to ⚙️ Set wallet

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/7

Updated command names to text_only, while Emodzi in Aliases
