### ISSUE TITLE
Seems we have some troubles with readme.md?

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#43]
Please check info on readme.md. Is it actually?

Maybe it is needed to update screenshot, description, etc?

**Comment by Untoldhacker-Dev** [comment]
@bots-business This issue in queue, other issues Fixing in progress.

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/248b9ce4448f04b13cf2c2a7b50dda05211c5491
