### ISSUE TITLE
Use cooldownLib

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#44]
We have new lib - CooldownLib

use it for:
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/BB_Export_1634291956/commands/Bonus/_bonus.js

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/d5407ee398fdd0d596d28fc333a7abd4db5702ee
