### ISSUE TITLE
Bad name

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#46]
in stat command:

var totalUsers = Libs.ResourcesLib.anotherChatRes("status", "global").value()

why "status"? Use totalUsers for res name too!

**Comment by Untoldhacker-Dev** [comment]
Fixed: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/115e5403a5160603b020ee9f7212b942d513bb96
