### ISSUE TITLE
19 line in @ not needed?

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#48]
`var balance = Libs.ResourcesLib.userRes("balance")`

it is 19 line in @ 
seems it is not needed

**Comment by Untoldhacker-Dev** [comment]
It is needed. 
Because in command withdraw we have: `balance.add(+x)`
And `user.balance.add()` is not a function

**Comment by bots-business** [comment]
So we have:
- user.balance
- balance

it is not good. 

I think it is better add to @ this:

```
user.setBalance = function(amount){
   Libs.ResourcesLib.userRes("balance").add(amount)
} 

```
so in other commands we can use:
`user.setBalance(anyAmountHere)`

**Comment by bots-business** [comment]
Please reopen this issue

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/57
