### ISSUE TITLE
bad names for cooldown

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#50]
We have in _bonus.js now:

`let cooldown = Libs.CooldownLib.chat.getCooldown("GemBonusCooldown");`

Do we have any GemBonus? 
Why "Gem" ?

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/57
