### ISSUE TITLE
Do not use "ELSE" after "RETURN"

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#52]
```
if (user.telegramid == message) {
  Bot.sendMessage("Error: 404, User is not found!")
  return
} else Bot.blockChat(message)
Bot.sendMessage(
  "Successfully banned: " +message
)
```

} else - is not needed here because you have "return" before

it can be easy:
```
if (user.telegramid == message) {
  Bot.sendMessage("Error: 404, User is not found!")
  return
}

Bot.blockChat(message)
Bot.sendMessage("Successfully banned: " + message)
```

**Comment by bots-business** [comment]
unbun is simular. "Else" is not needed too

**Comment by bots-business** [comment]
onGetIdToSend.js  - simular. Else is not needed

**Comment by bots-business** [comment]
_withdraw.js - simular

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/57

**Comment by bots-business** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/BB_Export_1634291956/commands/Withdraw/_withdraw.js - not fixed
