### ISSUE TITLE
Do not use + for positive numbers

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#54]
in bonus:
`balance.add(+parseFloat(bonus))`

it can be just:
`balance.add(parseFloat(bonus))`

because using "+" here is not good practic:
We have: 
+(1) = 1  

and +(1)=1 always. So "+" is not important

**Comment by bots-business** [comment]
in start.js - Line 64:
 status.add(+1)

just:
 status.add(1)

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/57
