### ISSUE TITLE
wallet is undefined in _setWallet.js

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#56]
```
User.setProperty("wallet", message, "string")
Bot.sendMessage("*✏️☑️ Wallet set To :* " + user.wallet + "")
```

but user.wallet - can be undefined

you need use:
`Bot.sendMessage("*✏️☑️ Wallet set To :* " + message + "")`

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/57
