### ISSUE TITLE
Need several Admin Panels

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#58]
Seems we have 1 huge Admin Panel now:

![image](https://user-images.githubusercontent.com/38240269/142182584-3e2b20e6-c5e6-482e-8893-f7650faf4080.png)

I think more pretty separate it for several APs:
- Bot settings (AdminID, CurrencyName)
- Bonus settings
- Withdrawal settings

**Comment by bots-business** [comment]
Also it is possible to fix header:

![image](https://user-images.githubusercontent.com/38240269/142183179-737980c1-be13-415b-b352-fea6f603eaad.png)

But I think several panels - more pretty

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/59
Changed panel header.

**Comment by bots-business** [comment]
Please update screenshot in Readme.md
