### ISSUE TITLE
Bad names for folders

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#6]
![image](https://user-images.githubusercontent.com/38240269/137605979-e4469f9f-e015-42a4-9d07-ba8f198ec1d4.png)

It is really not good. 

https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/tree/BB_Export_1634291956/commands

![image](https://user-images.githubusercontent.com/38240269/137606010-5ace7eb9-14d2-4a98-871c-6e7627ba24c3.png)

You have there:
- stat
- balance, withdraw
- edit-currency
- panel

Why do you use all this command in one folder with name "commands"? 
It can be several folders! Like "Options", "Balance"(?), "Statistic" (?)

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/pull/7

**Solved**
