### ISSUE TITLE
Bad names 

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#61]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/blob/BB_Export_1634291956/commands/Stat/_stat.js

`var totalUsers = Libs.ResourcesLib.anotherChatRes("status", "global").value()`

if you use totalUsers name also must be totalUsers not "status"

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/75748849f64c145b776a792fe094c5bbe3728ae5
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/9193a891263373b2ffce26c8d454a78efcbfa56c
