### ISSUE TITLE
Bad functions names

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#64]
withdrawRequest.js

names for functions is bad:
- needMoreAmount  > it is sendMsgNeedMoreAmount
- needLessAmount() > sendMsgLessAmount
-  isInvalid() > sendMessageIncorrectAmount

and etc.

**Comment by bots-business** [comment]
do not close issue after fixing. Please assign tag

**Comment by Untoldhacker-Dev** [comment]
Fixed: #66
