### ISSUE TITLE
not needed ""

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#67]
in _setWallet.js

`Bot.sendMessage("*✏️☑️ Wallet set To :* " + message + "")`

change to 
`Bot.sendMessage("*✏️☑️ Wallet set To :* " + message)`

**Comment by Untoldhacker-Dev** [comment]
Fixed: https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/7a9c8a11aa4c544cfb0fef3cbbc5c6ccddd07d20
