### ISSUE TITLE
Reduce itertions for blocking users

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#8]
It is possible to reduce iterations:
https://help.bots.business/iterations.-how-to-reduce-theys#what-it-is-iteration

100 incoming messages in blocked chat with method Bot.blockChat(chat.id)

But now we do not use method Bot.blockChat:
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/search?q=blockChat

I think it is possible to make hard and soft user block

We can make automatic hard block if user continue spaming after soft block

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/c91ddd9670ddf247e58fbe82240e5d222ab04f06
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/fdc99ad0a0a2fbe2eaa6eaeb30fb80f4d5f94725
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/f35b8a53bf3014d2183357e19f06e1afa30cdbb1
