### ISSUE TITLE
Bad naming for variables

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/friendly-octo-fortnight#9]
In this code you have bad naming.

```
function isAdmin() {
  var admin = Bot.getProperty("admin_chat")
  if (user.telegramid == admin) {
    return true
  }
  return false
}
```

What it is?
`var admin = Bot.getProperty("admin_chat");
`

you read admin_chat so it must be admin chat too!
`var admin_chat = Bot.getProperty("admin_chat");
`

**Comment by bots-business** [comment]
then you have
if (user.telegramid == admin) {

so it is NOT admin_chat!

it is adminTgId !

**Comment by Untoldhacker-Dev** [comment]
https://github.com/Untoldhacker-Dev/friendly-octo-fortnight/commit/705d3d4c0056b8c00fbc95d9ebf8732524e0ef12
